### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by xiaoning-shu** [ganji15/HiGANplus#1]
请问你们上传的代码用指示的指令能否执行？ 
为什么我这里会报错。
RuntimeError: The default implementation of __deepcopy__() for non-wrapper subclasses only works for subclass types that implement new_empty() and for which that function returns another instance of the same subclass. You should either properly implement new_empty() for your subclass or override __deepcopy__() if it is intended behavior for new_empty() to return an instance of a different type.

**Comment by htnha** [comment]
I got this error, how to fix that?
