### ISSUE TITLE
Questions about model training

### ISSUE THREAD

**Issue by hmppt** [ganji15/HiGANplus#11]
I want to know how to do multi-gpu training? I have four GPUs, and modify the configuration file as follows:
![image](https://user-images.githubusercontent.com/43752397/236467358-902112fa-e1a1-475a-b2a3-2792a098733d.png)
but it reported an error: 
![image](https://user-images.githubusercontent.com/43752397/236467523-2a81cd9b-ed6a-470c-9c33-c5d5141a2c77.png)

And i also want to know how to continue training from the previous checkpoint？
Thank you！

**Comment by ganji15** [comment]
Hi, @hmppt 

1. You must revise the ```'train.py'``` to support the multi-GPU training, such as

```python
import torch.distributed as dist


## multi-gpu training settings
parser.add_argument('--init-method', type=str, default='tcp://127.0.0.1:12345')
parser.add_argument('--backbend', type=str, default='nccl')
parser.add_argument('--local_rank', type=int)
parser.add_argument('--world-size', type=int, default=2)


if __name__ == '__main__':
    args = parser.parse_args()
    dist.init_process_group(backend=args.backbend)
```

2.  The provided code also doesn't support resuming from the previous checkpoint; thus, you have to mannually revise the code by yourself (such as saving & restoring the contexts during training).


Thanks.
