### ISSUE TITLE
Error for large imaginary component in fid_kid_is.py

### ISSUE THREAD

**Issue by SidraHanif180** [ganji15/HiGANplus#12]
Hi,

Thanks for sharing the code. 

I am training the HiGAN+ network from scratch on the IAM dataset, and it gave me an error for a large imaginary component in the function fid_kid_is.py.

The error is returned by the following line:
raise ValueError('Imaginary component {}'.format(m))

Do you like to share insight on the reason that may prompt this error? Thanks.

**Comment by nek0peko** [comment]
I got the same issue. I'd appreciate it if u could let me know if u have resolved this problem.

**Comment by nek0peko** [comment]
I simply replaced the code to calculate the covmean in calculate_frechet_distance(), and solved the problem. @SidraHanif180 ```python

    # Get imaginary component
    # covmean, _ = linalg.sqrtm(sigma1.dot(sigma2), disp=False)

    # Proved to be feasible, but slow
    # covmean = linalg.fractional_matrix_power(sigma1.dot(sigma2), 0.5) 

    # Proved to be feasible
    covmean = np.cov(sigma1, sigma2)

```

**Comment by ganji15** [comment]
@nek0peko  Thanks!
