### ISSUE TITLE
Why does real_imgs have -1 during training？

### ISSUE THREAD

**Issue by hmppt** [ganji15/HiGANplus#13]
@ganji15 
I'm training HiGAN+, I printed real_imgs during training and found -1 in it.
![image](https://github.com/ganji15/HiGANplus/assets/43752397/e0c34bc7-9d9d-400b-aeb7-3be9142786c3)
The upper part is recn_img, and the second half is real_img. Why do these -1s exist?

Also can you explain the ’recn_l1_loss(img1, img2, img_lens)‘ function?  What I know so far is that this function is a variable-length l1 loss, i want to know more details.

Thanks very much!

**Comment by ganji15** [comment]
@hmppt 

The pixel values of images are normalized into the range [-1, 1].

'recn_l1_loss' calculate the l1 loss of two tensors. For more details,  you can refer to the source code.
