### ISSUE TITLE
Why is the image generated by HIGAN+ inconsistent with the original image？

### ISSUE THREAD

**Issue by hmppt** [ganji15/HiGANplus#14]
Hi! @ganji15 

I have two questions: Why is the segmentation of the generated image different from the original image? As shown in the figure below, in the original image "r" and "y" are not split, but in generated image "r" and "y" are split. 

![image](https://github.com/ganji15/HiGANplus/assets/43752397/fb0e89be-9ea2-4449-bfb4-3a5b5903f99d)

Another question is why the shading of the generated image is different from the original image

![image](https://github.com/ganji15/HiGANplus/assets/43752397/c1be8c0e-f87a-4570-b129-05ba704b3982)

I'm looking forward for your reply！

**Comment by ganji15** [comment]
@hmppt  Human's handwriting can be very arbitrary, and thus there indeed exists a limit to the generator for synthesizing handwritten samples. In other words, we don't guarantee that the generated images have the exact same contents and styles pixel-by-pixel.
