### ISSUE TITLE
作者您好！如何构建跟英文手写数据集相同的数据集格式？

### ISSUE THREAD

**Issue by 13209413223** [ganji15/HiGANplus#17]

**Comment by 13209413223** [comment]
如何把“藏语”语种的数据集构建成和您发的数据集格式相同的hdf5文件？

**Comment by ganji15** [comment]
@13209413223  https://github.com/ganji15/HiGANplus/blob/main/HiGAN%2B/lib/datasets.py#L205

**Comment by 13209413223** [comment]
您好！数据集标注方式是如何处理的？求助

**Comment by ganji15** [comment]
@13209413223 

需要你人工地给每个图片设置文本行标签。
