### ISSUE TITLE
Is this model Zero-shot Handwriting imitation?

### ISSUE THREAD

**Issue by caigun** [ganji15/HiGANplus#19]
As described in the title, I would like to know if the model can absorb the unseen handwriting images and transfer the style of the handwriting to generate new texts.
My understanding is that in the writer embedding, the dimension of the embedding is set to the number of writers in the training set, i.e., the IAM dataset. Thus, it is not a zero-shot model. However, this idea and structure of the model should be robust enough to do so.

**Comment by ganji15** [comment]
Hi, @caigun 

The dimension of the style embedding is **NOT** set to the number of writers, instead, it can be any number of the dimensions (which depend on the intermediate feature dimension of **StyleEncoder** ).

Specifically, the model contains a **StyleEncoder**  that can encode **any given handwriting image (even not seen before)** into a fixed-sized style vector, which can be further fed into the **Generator** to synthesize other arbitrary images with similar calligraphic styles.

Hope that I have explained it clearly. 

Thanks.

**Comment by caigun** [comment]
Thanks for the explanation. I wonder if there is a folder where the reference handwriting images can be placed since I couldn't find them in the recipe.
Also, I can only run the inference part of the model. For the training part, I had bad luck. I suspect that the version of my packages was different, but you only provided the requirements for Python, the platform, and PyTorch.

**Comment by ganji15** [comment]
Hi, @caigun 

1.  you can refer to **issue #2** and correspondingly revise the training code.
> I have updated the code so that you can reproduce specific calligraphic styles from images (e.g., PNG, JPG). The steps are given as follows:
> 
> 1. Download the newest repository ` git clone https://github.com/ganji15/HiGANplus.git`
> 2. Put your reference images into the directory `./data/image_samples/`
> 3. Run the command
>    `python eval_demo.py --config ./configs/gan_image.yml --ckpt ./pretrained/deploy_HiGAN+.pth --mode style`
> 
> After that, you can reproduce specific styles given prior images/samples.
> 
> ![demo](https://user-images.githubusercontent.com/3733327/217192418-bf0e695f-1bc9-44b1-a0ee-071efd4fe04c.png)

2. Perhaps you should install the missing packages according to the error messages.

Good luck!
