### ISSUE TITLE
我想请问一下，gan_iam.yml只是在训练一个GAN网络吗？

### ISSUE THREAD

**Issue by hmppt** [ganji15/HiGANplus#5]
你好，HiGAN+的作者：
我是一名初学者，请原谅我问一下很低级细节的问题。我想请问gan_iam.yml只是在训练一个GAN网络（文章中的G和D）吗？文章中描述的R和I（复用E）是预训练好的吗？其他的yml文件，比如ocr_iam.yml以及wid_iam.yml是否可以直接利用来训练R和I（复用E），需要额外的数据集吗？以及如果我想单独训练一个I需要什么命令？
感谢！

**Comment by ganji15** [comment]
@hmppt 
Yes, you can use ocr_iam.yml and iam_iam.yml to train the recognizer R and writer identifier I respectively.

**Comment by hmppt** [comment]
你好，很抱歉打扰您。最近我在您的基础上再训练一个style encoder，类似于HiGAN+论文中的“Regularization with reconstruction”。如下图所示，我的想法是黑框的E和红框的E结构相同但参数不同，我想训练红框的E用于其他任务。
![image](https://user-images.githubusercontent.com/43752397/233604570-b1b3802c-9b7c-47cd-90dc-4d15d39f5b6a.png)
正如您论文中提到的，E与I是共用一个网络结构和参数，但是参考您的代码后，我发现E的训练是与GAN同时进行的，而I的训练是单独进行的，您可以给我更清晰地讲解E与I的关系和训练过程吗？如果我想训练这个红框E，我是否应该在如下图中红框标注的位置进行代码的增改而不是WriterIdentifyModel呢？
![image](https://user-images.githubusercontent.com/43752397/233609749-e7b8a388-0667-4a6b-ae90-2e5efeb1936f.png)
万分感谢！
