### ISSUE TITLE
How to add a new style?

### ISSUE THREAD

**Issue by htnha** [ganji15/HiGANplus#7]
I write some new handwriting styles, how can I add them to generate with style

**Comment by hmppt** [comment]
You can refer to this answer: https://github.com/ganji15/HiGAN/issues/5.
And I also use my own handwritten fonts and found that HiGAN+ does not imitate well. You can refer to 
 this answer: https://github.com/ganji15/HiGANplus/issues/3#issuecomment-1484021962
