### ISSUE TITLE
您好，请问testset_words64_OrgSz.hdf5中的数据是如何得到的？

### ISSUE THREAD

**Issue by hmppt** [ganji15/HiGANplus#8]
您好，
我下载了IAM手写词级数据集，但是我并不清楚testset_words64_OrgSz.hdf5中的标签wids是怎么得到的。具体来说，我下载了ascii 格式的汇总元信息，但是没有发现writer id这一项。
![image](https://user-images.githubusercontent.com/43752397/228202425-c0d7c3c1-cf3b-49ed-b708-8e8b2e1400cd.png)
![image](https://user-images.githubusercontent.com/43752397/228228751-b62801c5-07fd-46c2-8199-02da82930121.png)

**Comment by ganji15** [comment]
Hi, @hmppt 

Please check the annotation file "froms.txt".

![Form](https://user-images.githubusercontent.com/3733327/232234537-a2eaa43b-05b3-4578-a92d-a01edaea6410.png)

**Comment by hmppt** [comment]
Allow me to ask one more simple question：If I want to use the IAM dataset for training, do I need to resize the image data to 64*32*(len(label))? The former is height, the latter is length.

**Comment by ganji15** [comment]
@hmppt 
You don't need to resize the image to 6432(len(label)), and you just need to keep the 64-pixel height with preserving the original aspect ratio of each image.
